disabled_rules: # rule identifiers to exclude from running
  - line_length
  - function_body_length
  - valid_docs
  - file_length
  - type_body_length
  - variable_name_min_length
included: # paths to include during linting. `--path` is ignored if present.
  - ../Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .
